# install the necessary packages
- name: install packages
  yum:
    name: '{{ item.name }}'
    state: '{{ item.state }}'
  with_items: '{{ auditd_packages }}'

# enable and start the auditd service
- service:
    name: auditd
    state: started
    enabled: yes

- name: generate audit.d/audit.rules
  template:
    src: audit.rules.j2
    dest: /etc/audit/rules.d/audit.rules
    mode: 0640
  notify:
    - restart auditd
